core/urls.py
from django.contrib import admin
from django.urls import path
from .views import UserDataFormView, HomeView, UserDataListView, ShippingDataFormView, ShippingDataListView
app_name = 'core'
urlpatterns = [
    path('userdataform/', UserDataFormView.as_view(), name='userdataform'),
    path('', HomeView.as_view(), name='homepage'),
    path('userdetails/', UserDataListView.as_view(), name='userdatalist'),
    path('shippingdataform/', ShippingDataFormView.as_view(), name='shippingform'),
    path('shippingdetails/', ShippingDataListView.as_view(), name='shippingdatalist')

]

lab10/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]

core/models.py
from django.db import models


# Create your models here.

class UserDataModel(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.CharField(max_length=50)


class ShippindDataModel(models.Model):
    receiver_first_name = models.CharField(max_length=50)
    receiver_last_name = models.CharField(max_length=50)
    receiver_address = models.TextField()

core/forms.py
from django import forms


class UserDataForm(forms.Form):
    first_name = forms.CharField(required=True)
    last_name = forms.CharField(required=True)
    email = forms.CharField(required=True)


class ShippingDataform(forms.Form):
    receiver_first_name = forms.CharField(required=True)
    receiver_last_name = forms.CharField(required=True)
    receiver_address = forms.CharField(required=True)

core/views.py
from django.shortcuts import render, redirect

# Create your views here.
from django.views.generic import View, ListView
from .forms import UserDataForm, ShippingDataform
from .models import UserDataModel, ShippindDataModel


class UserDataFormView(View):
    def get(self, *args, **kwargs):
        form = UserDataForm()
        context = {
            'form': form
        }
        return render(self.request, 'userdataform.html', context)

    def post(self, *args, **kwargs):
        print(self.request.POST['first_name'])

        first_name = self.request.POST['first_name']
        last_name = self.request.POST['last_name']

        email = self.request.POST['email']
        print(email)
        UserDataModel.objects.get_or_create(first_name=first_name, last_name=last_name, email=email)

        return redirect('core:userdatalist')


class HomeView(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'homepage.html')


class UserDataListView(ListView):
    model = UserDataModel
    template_name = 'userdatadetailspage.html'


class ShippingDataFormView(View):
    def get(self, *args, **kwargs):
        return render(self.request, 'ShippingDataForm.html')

    def post(self, *args, **kwargs):

        first_name = self.request.POST['receiver_first_name']
        last_name = self.request.POST['receiver_last_name']

        email = self.request.POST['receiver_address']
        ShippindDataModel.objects.get_or_create(receiver_first_name=first_name, receiver_last_name=last_name, receiver_address=email)

        return redirect('core:shippingdatalist')
class ShippingDataListView(ListView):
    model = ShippindDataModel
    template_name = 'shippingdetailspage.html'

templates/ShippingDataForm.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}
pip
{% block content %}
    <div class="row">
    <form method="POST">
                  {% csrf_token %}
   <div class="form-group">
    <label for="first_name">Receiver First Name</label>
    <input type="text" class="form-control" id="first_name" name="receiver_first_name" placeholder="Receiver First Name">
  </div>
   <div class="form-group">
    <label for="last_name">Receiver Last Name</label>
    <input type="text" class="form-control" id="last_name" name="receiver_last_name" placeholder="Last Name">
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="text" class="form-control" id="email" name="receiver_address" aria-describedby="emailHelp" placeholder="Enter address">
    <small id="emailHelp" class="form-text text-muted">We'll never share your address with anyone.</small>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>News Scraper</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href={% url 'core:homepage' %}>Lab 10 with two forms</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarText">
    <ul class="navbar-nav mr-auto">
      <li>
        <a class="nav-link" href={% url 'core:userdataform' %}>User Data Form</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={% url 'core:shippingform' %}>Shipping Data Form</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href={%  url 'core:userdatalist' %}>User Details Page</a>
      </li>
        <li class="nav-item">
        <a class="nav-link" href={% url 'core:shippingdatalist' %}>Shipping Details Page</a>
      </li>
    </ul>
    <span class="navbar-text">
      Navbar text with an inline element
    </span>
  </div>
</nav>

    <main role="main" class="container">

      <div class="starter-template">
        {%  block content %}


        {%  endblock %}
      </div>

    </main>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

</body>
</html>

templates/homepage.html
{%  extends 'base.html' %}
{%  block content %}
    <p>Welcome to home. Use linka to go to forms.</p>
{%  endblock %}

templates/shippingdetailspage.html
{% extends 'base.html'  %}

{% block content %}

{% for item in object_list %}

    {{ item.receiver_first_name }} - {{ item.receiver_last_name }} - {{ item.receiver_address }}

{% endfor %}

{% endblock content %}

templates/userdatadetailspage.html
{% extends 'base.html'  %}

{% block content %}

{% for item in object_list %}

    {{ item.first_name }} - {{ item.last_name }} - {{ item.email }}

{% endfor %}

{% endblock content %}

templates/userdataform.html
{% extends 'base.html' %}
{#{% load crispy_forms_tags %}#}
pip
{% block content %}
    <div class="row">
    <form method="POST">
                  {% csrf_token %}
   <div class="form-group">
    <label for="first_name">First Name</label>
    <input type="text" class="form-control" id="first_name" name="first_name" placeholder="First Name">
  </div>
   <div class="form-group">
    <label for="last_name">Last Name</label>
    <input type="text" class="form-control" id="last_name" name="last_name" placeholder="Last Name">
  </div>
  <div class="form-group">
    <label for="email">Email</label>
    <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Enter email">
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <button type="submit" class="btn btn-primary">Submit</button>
</form>
    </div>
{% endblock %}